### ISSUE TITLE
want installation instruction

### ISSUE THREAD

**Issue by syumai** [Code-Hex/gqldoc#1]
Hi, thank you for awesome tool!
I want to try this tool, but it seems there's no `cmd/gqldoc/main.go` or `gqldoc/main.go`.
Please add them and give an installation instruction on README.md.

**Comment by Code-Hex** [comment]
Thanks for creating an issue.
I have added `cmd/gqldoc/main.go` code at [here](https://github.com/Code-Hex/gqldoc/commit/2cdb66575d9005998327835e0339393a1f894ec7) and Fixed README for adding installation instruction at [here](https://github.com/Code-Hex/gqldoc/commit/effe7292b7a3ab5f4cd83f6f7a8d9779cb9201d7).

If you have any question, please re-open this issue or create a new issues. thx
